[versions]
agp = "9.1.1"
kotlin = "2.2.20"
googleServices = "4.4.2"

[libraries]
# Add libraries here if needed

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
